// generated by gostringer -type=Protocol; DO NOT EDIT

package protocols

import "fmt"

const _Protocol_name_gostringer = "TCPUDPend"

var _Protocol_index_gostringer = [...]uint8{0, 3, 6, 9}

func (i Protocol) GoString() string {
	i -= 1
	if i >= Protocol(len(_Protocol_index_gostringer)-1) {
		return fmt.Sprintf("protocols.Protocol(%d)", i+1)
	}
	return "protocols." + _Protocol_name_gostringer[_Protocol_index_gostringer[i]:_Protocol_index_gostringer[i+1]]
}
